"use client";

import { useState, useEffect, useCallback } from "react";
import {
  BarChart3,
  Download,
  Copy,
  Check,
  RefreshCw,
  Loader2,
  CheckCircle2,
  TrendingUp,
  TrendingDown,
  Minus,
  FileText,
  ExternalLink,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import type { Asset, Stance, Facet, AnalysisReport } from "@/lib/contracts";
import {
  copyReportToClipboard,
  downloadReportMarkdown,
} from "@/lib/report-utils";

/* ── Generate Markdown from a report ── */
function generateMarkdown(report: AnalysisReport): string {
  const stanceEmoji = report.stance === "bullish" ? "📈" : report.stance === "bearish" ? "📉" : "➖";
  const confidenceStr = report.confidence != null ? `${Math.round(report.confidence * 100)}%` : "N/A";

  let md = `# ${stanceEmoji} ${report.asset} 市場分析研報\n\n`;
  md += `> **Generated by AlphaSonar Agent**\n\n`;
  md += `---\n\n`;
  md += `## 基本資訊\n\n`;
  md += `| 欄位 | 內容 |\n|------|------|\n`;
  md += `| Run ID | \`${report.run_id}\` |\n`;
  md += `| 標的 | ${report.asset} |\n`;
  md += `| 研究問題 | ${report.question} |\n`;
  md += `| 研判方向 | **${report.stance.toUpperCase()}** |\n`;
  md += `| 跨因子置信度 | **${confidenceStr}** |\n`;
  md += `| 數據截止日 | ${report.cutoff} |\n\n`;

  if (report.facet_stances && Object.keys(report.facet_stances).length > 0) {
    md += `## 各因子方向判定\n\n`;
    md += `| 因子 | 方向 |\n|------|------|\n`;
    for (const [facet, stance] of Object.entries(report.facet_stances)) {
      md += `| ${facet} | ${(stance as string).toUpperCase()} |\n`;
    }
    md += `\n`;
  }

  if (report.claims.length > 0) {
    md += `## 核心判斷條目 (Claims)\n\n`;
    report.claims.forEach((claim, i) => {
      md += `### ${i + 1}. [${claim.role.toUpperCase()}] ${claim.facet}\n\n`;
      md += `${claim.text}\n\n`;
      if (claim.evidence_ids.length > 0) {
        md += `**引證**: ${claim.evidence_ids.map((id) => `\`${id}\``).join(", ")}\n\n`;
      }
    });
  }

  if (report.evidence.length > 0) {
    md += `## 證據清單 (Evidence)\n\n`;
    report.evidence.forEach((ev) => {
      md += `### ${ev.evidence_id}\n\n`;
      md += `- **面向**: ${ev.facet}\n`;
      md += `- **摘要**: ${ev.summary}\n`;
      md += `- **方向傾向**: ${ev.stance_hint.toFixed(2)}\n`;
      if (ev.sources.length > 0) {
        md += `- **來源**:\n`;
        ev.sources.forEach((src) => {
          md += `  - [${src.source}](${src.source_url}) — ${src.content_reference.excerpt} (${src.fetched_at})\n`;
        });
      }
      md += `\n`;
    });
  }

  md += `---\n\n`;
  md += `*本報告由 AlphaSonar ReAct Agent 自動產生，僅供參考，不構成投資建議。*\n`;
  md += `*HOYA BIT 提供 100% 法幣銀行信託隔離保障。*\n`;

  return md;
}

function downloadMarkdown(report: AnalysisReport) {
  const md = generateMarkdown(report);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${report.asset}_report_${report.run_id.slice(0, 8)}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/* ── Static demo report (used when backend is unavailable) ── */
const DEMO_REPORT: AnalysisReport = {
  run_id: "demo-report-001",
  asset: "BTC",
  question: "市場上認為 BTC 短期盤整，請驗證正反證據與多空主力佈局。",
  stance: "neutral",
  confidence: 0.82,
  cutoff: "2026-07-25 UTC",
  facet_stances: { technical: "neutral", positioning: "bullish", fundamental: "bullish", sentiment: "neutral" },
  claims: [
    {
      text: "BTC 價格於 66,500 - 68,000 美元平穩震盪，多空資金比保持中性偏多。",
      evidence_ids: ["EV-BTC-TECH-01", "EV-BTC-POS-01"],
      facet: "technical",
      role: "fact",
    },
    {
      text: "主力合約持倉量 (OI) 增加 2.4%，但資金費率保持在 0.008% 低位，顯示無過度開槓桿現象。",
      evidence_ids: ["EV-BTC-POS-02"],
      facet: "positioning",
      role: "inference",
    },
    {
      text: "鏈上巨鯨地址近 72 小時淨流入 4,200 BTC，長線籌碼持續沉澱於冷錢包。",
      evidence_ids: ["EV-BTC-FUND-01"],
      facet: "fundamental",
      role: "conclusion",
    },
    {
      text: "風控提示：若跌破 65,200 美元強支撐位，可能引發短期止損賣壓，建議保持 DCA 策略。",
      evidence_ids: ["EV-BTC-RISK-01"],
      facet: "sentiment",
      role: "risk",
    },
  ],
  evidence: [
    {
      evidence_id: "EV-BTC-TECH-01",
      facet: "technical",
      summary: "CoinGecko BTC/USDT 4H K線均線呈收斂，RSI 位於 52.4，方向中立。",
      stance_hint: 0.05,
      related_claim: ["claim-1"],
      sources: [
        {
          source: "CoinGecko API",
          source_url: "https://api.coingecko.com/v3/coins/bitcoin",
          fetched_at: "2026-07-25 16:29 UTC",
          content_reference: { locator: "ohlc/4h", excerpt: "BTC/USDT 4H Range 66500-68000, RSI 52.4" },
        },
      ],
    },
  ],
};

export function ReportsView() {
  const [reports, setReports] = useState<AnalysisReport[]>([DEMO_REPORT]);
  const [loading, setLoading] = useState(true);
  const [backendConnected, setBackendConnected] = useState(false);
  const [expandedReport, setExpandedReport] = useState<string | null>(null);

  const fetchReports = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/v1/runs");
      if (res.ok) {
        const data = await res.json();
        const runs = (data.runs ?? []) as Record<string, unknown>[];
        // Filter runs that actually have a report (non-null stance)
        const validReports: AnalysisReport[] = runs
          .filter((r) => r.stance && r.claims)
          .map((r) => ({
            run_id: String(r.run_id ?? ""),
            asset: String(r.asset ?? "BTC") as Asset,
            question: String(r.question ?? ""),
            stance: String(r.stance ?? "neutral") as Stance,
            confidence: typeof r.confidence === "number" ? r.confidence : null,
            cutoff: String(r.cutoff ?? ""),
            facet_stances: (r.facet_stances ?? {}) as Partial<Record<Facet, Stance>>,
            claims: (Array.isArray(r.claims) ? r.claims : []).map((c: Record<string, unknown>) => ({
              text: String(c.text ?? ""),
              evidence_ids: Array.isArray(c.evidence_ids) ? c.evidence_ids.map(String) : [],
              facet: String(c.facet ?? "technical") as Facet,
              role: String(c.role ?? "fact") as AnalysisReport["claims"][number]["role"],
            })),
            evidence: (Array.isArray(r.evidence) ? r.evidence : []).map((e: Record<string, unknown>) => ({
              evidence_id: String(e.evidence_id ?? ""),
              facet: String(e.facet ?? "technical") as Facet,
              summary: String(e.summary ?? ""),
              stance_hint: typeof e.stance_hint === "number" ? e.stance_hint : 0,
              related_claim: Array.isArray(e.related_claim) ? e.related_claim.map(String) : [],
              sources: Array.isArray(e.sources)
                ? e.sources.map((s: Record<string, unknown>) => ({
                    source: String(s.source ?? ""),
                    source_url: String(s.source_url ?? ""),
                    fetched_at: String(s.fetched_at ?? ""),
                    content_reference: {
                      locator: String((s.content_reference as Record<string, unknown>)?.locator ?? ""),
                      excerpt: String((s.content_reference as Record<string, unknown>)?.excerpt ?? ""),
                    },
                  }))
                : [],
            })),
          }));

        // 後端有回應就是「已連接」，跟「有沒有研報」是兩件事——
        // 原本這兩種狀態被混在一起，後端明明連得上、只是還沒有任何
        // 研報時，會被判定成「未連接」並且無聲換成寫死的 BTC demo
        // report，畫面上看不出使用者剛剛分析的其實是別的幣種。
        setBackendConnected(true);
        setReports(validReports);
      } else {
        setReports([DEMO_REPORT]);
        setBackendConnected(false);
      }
    } catch {
      setReports([DEMO_REPORT]);
      setBackendConnected(false);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchReports();
  }, [fetchReports]);

  return (
    <div className="chat-scroll flex-1 overflow-y-auto p-6 md:p-8">
      <div className="mx-auto max-w-4xl space-y-6">
        {/* Header */}
        <div className="flex flex-col gap-1 border-b border-outline-variant pb-5">
          <div className="flex items-center gap-2 text-primary font-bold text-headline-lg">
            <BarChart3 className="h-6 w-6 text-secondary" />
            <h2>Intelligence Reports Gallery</h2>
          </div>
          <p className="text-body-md text-secondary">
            正式出具的機構級市場研報與風控合規備份。可下載 Markdown 格式報告。
          </p>
        </div>

        {/* Connection status banner */}
        {!loading && (
          <div
            className={`flex items-center justify-between rounded-xl border px-4 py-2.5 text-[12px] ${
              backendConnected
                ? "border-emerald-200 bg-emerald-50/50 text-emerald-800"
                : "border-amber-200 bg-amber-50/50 text-amber-800"
            }`}
          >
            <div className="flex items-center gap-3">
              <CheckCircle2 className="h-4 w-4 flex-shrink-0" />
              <span>
                {backendConnected
                  ? reports.length > 0
                    ? `已連接後端 — ${reports.length} 份研報可供檢閱與下載`
                    : "已連接後端 — 尚無已完成的研報記錄"
                  : "後端未連接，顯示示範報告 (Demo Mode)"}
              </span>
            </div>
            <button
              onClick={fetchReports}
              disabled={loading}
              className="flex items-center gap-1.5 rounded-lg border border-outline-variant px-3 py-1 text-xs hover:bg-surface-container-low transition-colors disabled:opacity-50"
            >
              <RefreshCw className={`h-3.5 w-3.5 ${loading ? "animate-spin" : ""}`} />
              刷新
            </button>
          </div>
        )}

        {/* Loading */}
        {loading && (
          <div className="flex items-center justify-center py-12">
            <Loader2 className="h-6 w-6 animate-spin text-primary" />
            <span className="ml-3 text-body-md text-secondary">載入研報中...</span>
          </div>
        )}

        {/* Empty state — connected but no reports yet. Never fall back to
            DEMO_REPORT here: that would silently show a hardcoded BTC
            report with no indication it isn't the user's actual analysis. */}
        {!loading && backendConnected && reports.length === 0 && (
          <div className="flex flex-col items-center gap-2 rounded-2xl border border-dashed border-outline-variant py-16 text-center">
            <FileText className="h-8 w-8 text-secondary" />
            <p className="text-body-md font-medium text-primary">尚無已完成的研報</p>
            <p className="text-body-sm text-secondary">
              回到 Workspace 執行一次分析，完成後這裡會顯示可下載的研報。
            </p>
          </div>
        )}

        {/* Reports list */}
        {!loading && reports.map((report) => (
          <ReportCard key={report.run_id} report={report} />
        ))}

        {/* Trust notice */}
        <div className="rounded-2xl border border-emerald-200 bg-emerald-50/50 p-5 flex items-center gap-4">
          <CheckCircle2 className="h-8 w-8 text-emerald-600 flex-shrink-0" />
          <div>
            <h4 className="font-bold text-primary text-body-lg">
              HOYA BIT 100% 法幣信託隔離聲明
            </h4>
            <p className="text-body-md text-secondary">
              所有研報自動嵌入信託安全指引。HOYA BIT 平台用戶資金享 100% 新台幣銀行信託隔離，資產絕對安全。
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

/* ── Report Card Component ── */

function ReportCard({ report }: { report: AnalysisReport }) {
  const [copied, setCopied] = useState(false);
  const [expanded, setExpanded] = useState(false);

  async function handleCopy() {
    const ok = await copyReportToClipboard(report);
    if (ok) {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }

  return (
    <article className="ai-card rounded-2xl border border-outline-variant bg-surface-container-lowest p-6 space-y-4">
      {/* Report Header */}
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-outline-variant pb-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="rounded-pill bg-primary px-3 py-1 font-mono text-[12px] font-bold text-on-primary">
              {report.asset} / USD
            </span>
            <StanceBadge stance={report.stance} />
          </div>
          <h3 className="mt-2 text-headline-md font-bold text-primary">
            {report.question}
          </h3>
          <p className="mt-1 font-mono text-[11px] text-secondary">
            Run: {report.run_id} | Cutoff: {report.cutoff}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button
            variant="secondary"
            className="gap-1.5 text-[12px]"
            onClick={handleCopy}
          >
            {copied ? (
              <>
                <Check className="h-3.5 w-3.5 text-emerald-600" />
                <span className="text-emerald-600 font-bold">已複製！</span>
              </>
            ) : (
              <>
                <Copy className="h-3.5 w-3.5 text-secondary" />
                <span>複製研報</span>
              </>
            )}
          </Button>
          <Button
            variant="secondary"
            className="gap-1.5 text-[12px]"
            onClick={() => downloadReportMarkdown(report)}
          >
            <Download className="h-4 w-4" /> 下載 Markdown
          </Button>
        </div>
      </div>

      {/* Key Takeaways Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
        <div className="rounded-xl border border-outline-variant bg-surface-container-low p-3.5">
          <span className="text-label-caps text-secondary uppercase font-semibold">跨因子一致度</span>
          <p className="font-mono text-headline-md font-bold text-primary mt-1">
            {report.confidence != null ? `${Math.round(report.confidence * 100)}%` : "N/A"}
          </p>
        </div>
        <div className="rounded-xl border border-outline-variant bg-surface-container-low p-3.5">
          <span className="text-label-caps text-secondary uppercase font-semibold">稽核引證項目</span>
          <p className="font-mono text-headline-md font-bold text-primary mt-1">
            {report.claims.length} 判斷 / {report.evidence.length} 證據
          </p>
        </div>
        <div className="rounded-xl border border-outline-variant bg-surface-container-low p-3.5">
          <span className="text-label-caps text-secondary uppercase font-semibold">因子覆蓋</span>
          <p className="font-mono text-body-md font-bold text-primary mt-1">
            {report.facet_stances ? Object.keys(report.facet_stances).length : 0} / 4 面向
          </p>
        </div>
      </div>

      {/* Facet Stances */}
      {report.facet_stances && Object.keys(report.facet_stances).length > 0 && (
        <div className="flex flex-wrap gap-2 pt-1">
          {Object.entries(report.facet_stances).map(([facet, stance]) => (
            <FacetStancePill key={facet} facet={facet} stance={stance as Stance} />
          ))}
        </div>
      )}

      {/* Expandable Claims Section */}
      <div className="border-t border-outline-variant pt-3">
        <button
          onClick={() => setExpanded(!expanded)}
          className="flex items-center gap-2 text-[13px] font-semibold text-primary hover:text-primary/80 transition-colors"
        >
          <FileText className="h-4 w-4" />
          {expanded ? "收起判斷條目" : `展開判斷條目 (${report.claims.length})`}
        </button>

        {expanded && (
          <div className="mt-3 space-y-2.5 animate-fade-in">
            {report.claims.map((claim, idx) => (
              <div
                key={idx}
                className="rounded-xl border border-outline-variant bg-surface-container-low p-4"
              >
                <div className="flex items-center gap-2 mb-2">
                  <span
                    className={`rounded-pill px-2.5 py-0.5 text-[10px] font-bold uppercase tracking-wider ${
                      claim.role === "counter_evidence" || claim.role === "risk"
                        ? "bg-red-100 text-red-700"
                        : claim.role === "watch"
                        ? "bg-amber-100 text-amber-800"
                        : "bg-emerald-100 text-emerald-700"
                    }`}
                  >
                    {claim.role.replace("_", " ")}
                  </span>
                  <span className="text-[10px] text-secondary font-mono capitalize">
                    {claim.facet}
                  </span>
                </div>
                <p className="text-body-md leading-relaxed text-primary">
                  {claim.text}
                </p>
                {claim.evidence_ids.length > 0 && (
                  <div className="mt-2 flex flex-wrap gap-1.5">
                    {claim.evidence_ids.map((id) => (
                      <span
                        key={id}
                        className="inline-flex items-center gap-1 rounded-md border border-primary/20 bg-surface-container-lowest px-2 py-0.5 font-mono text-[10px] font-semibold text-primary"
                      >
                        <ExternalLink className="h-2.5 w-2.5" />
                        {id}
                      </span>
                    ))}
                  </div>
                )}
              </div>
            ))}

            {/* Evidence sources */}
            {report.evidence.length > 0 && (
              <div className="mt-4 rounded-xl border border-outline-variant bg-surface-container-low p-4">
                <h4 className="text-[11px] font-semibold uppercase tracking-widest text-secondary mb-2">
                  Evidence Sources ({report.evidence.length})
                </h4>
                <div className="space-y-2">
                  {report.evidence.map((ev) => (
                    <div key={ev.evidence_id} className="text-[11px] text-primary">
                      <span className="font-mono font-semibold">{ev.evidence_id}</span>
                      <span className="text-secondary"> — {ev.summary}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </article>
  );
}

/* ── Helper Components ── */

function StanceBadge({ stance }: { stance: Stance }) {
  const Icon = stance === "bullish" ? TrendingUp : stance === "bearish" ? TrendingDown : Minus;
  const color =
    stance === "bullish"
      ? "bg-emerald-100 text-emerald-700"
      : stance === "bearish"
      ? "bg-red-100 text-red-700"
      : "bg-amber-100 text-amber-800";

  return (
    <span className={`inline-flex items-center gap-1 rounded-pill px-3 py-0.5 text-label-caps font-bold ${color}`}>
      <Icon className="h-3 w-3" />
      {stance.toUpperCase()}
    </span>
  );
}

function FacetStancePill({ facet, stance }: { facet: string; stance: Stance }) {
  const color =
    stance === "bullish"
      ? "border-emerald-200 bg-emerald-50 text-emerald-700"
      : stance === "bearish"
      ? "border-red-200 bg-red-50 text-red-700"
      : "border-amber-200 bg-amber-50 text-amber-800";

  return (
    <span className={`rounded-lg border px-2.5 py-1 text-[11px] font-mono font-semibold capitalize ${color}`}>
      {facet}: {stance}
    </span>
  );
}
