import type { AnalysisReport } from "./contracts";

/**
 * Generate full Markdown representation of an AnalysisReport.
 * Prefers enhanced_report_md if available, otherwise generates structured Markdown.
 */
export function generateReportMarkdown(report: AnalysisReport): string {
  if (report.enhanced_report_md && report.enhanced_report_md.trim().length > 0) {
    return report.enhanced_report_md;
  }

  const stanceEmoji =
    report.stance === "bullish" ? "📈" : report.stance === "bearish" ? "📉" : "➖";
  const confidenceStr =
    report.confidence != null ? `${Math.round(report.confidence * 100)}%` : "N/A";

  let md = `# ${stanceEmoji} ${report.asset} 市場分析研報\n\n`;
  md += `> **Generated by AlphaSonar Agent**\n\n`;
  md += `---\n\n`;
  md += `## 基本資訊\n\n`;
  md += `| 欄位 | 內容 |\n|------|------|\n`;
  md += `| Run ID | \`${report.run_id}\` |\n`;
  md += `| 標的 | ${report.asset} |\n`;
  md += `| 研究問題 | ${report.question} |\n`;
  md += `| 研判方向 | **${report.stance.toUpperCase()}** |\n`;
  md += `| 跨因子置信度 | **${confidenceStr}** |\n`;
  md += `| 數據截止日 | ${report.cutoff} |\n\n`;

  if (report.facet_stances && Object.keys(report.facet_stances).length > 0) {
    md += `## 各因子方向判定\n\n`;
    md += `| 因子 | 方向 |\n|------|------|\n`;
    for (const [facet, stance] of Object.entries(report.facet_stances)) {
      md += `| ${facet} | ${(stance as string).toUpperCase()} |\n`;
    }
    md += `\n`;
  }

  if (report.claims && report.claims.length > 0) {
    md += `## 核心判斷條目 (Claims)\n\n`;
    report.claims.forEach((claim, i) => {
      md += `### ${i + 1}. [${claim.role.toUpperCase()}] ${claim.facet}\n\n`;
      md += `${claim.text}\n\n`;
      if (claim.evidence_ids.length > 0) {
        md += `**引證**: ${claim.evidence_ids.map((id) => `\`${id}\``).join(", ")}\n\n`;
      }
    });
  }

  if (report.evidence && report.evidence.length > 0) {
    md += `## 證據清單 (Evidence)\n\n`;
    report.evidence.forEach((ev) => {
      md += `### ${ev.evidence_id}\n\n`;
      md += `- **面向**: ${ev.facet}\n`;
      md += `- **摘要**: ${ev.summary}\n`;
      md += `- **方向傾向**: ${ev.stance_hint.toFixed(2)}\n`;
      if (ev.sources && ev.sources.length > 0) {
        md += `- **來源**:\n`;
        ev.sources.forEach((src) => {
          md += `  - [${src.source}](${src.source_url}) — ${src.content_reference.excerpt} (${src.fetched_at})\n`;
        });
      }
      md += `\n`;
    });
  }

  md += `---\n\n`;
  md += `*本報告由 AlphaSonar ReAct Agent 自動產生，僅供參考，不構成投資建議。*\n`;
  md += `*HOYA BIT 提供 100% 法幣銀行信託隔離保障。*\n`;

  return md;
}

/**
 * Copy report Markdown content to the user's clipboard.
 * Returns boolean indicating success.
 */
export async function copyReportToClipboard(report: AnalysisReport): Promise<boolean> {
  const text = generateReportMarkdown(report);
  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(text);
      return true;
    } else {
      // Fallback for non-secure contexts / legacy browsers
      const textArea = document.createElement("textarea");
      textArea.value = text;
      textArea.style.position = "fixed";
      textArea.style.left = "-999999px";
      textArea.style.top = "-999999px";
      document.body.appendChild(textArea);
      textArea.focus();
      textArea.select();
      const successful = document.execCommand("copy");
      document.body.removeChild(textArea);
      return successful;
    }
  } catch {
    return false;
  }
}

/**
 * Trigger file download of report as Markdown file.
 */
export function downloadReportMarkdown(report: AnalysisReport): void {
  const md = generateReportMarkdown(report);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  const filename = `${report.asset}_report_${(report.run_id || "report").slice(0, 8)}.md`;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
